/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.granite.tide.uibuilder {
	
	import mx.core.IUIComponent;
	import mx.validators.Validator;
	
	
    public class EntityProperty {
    	
    	public var property:String;
    	public var component:IUIComponent;
    	public var editorDataField:String;
    	public var percentWidth:int = -1;
    	public var validator:Validator;
    	public var parser:Function;
    	public var entityField:String;
    	public var bound:Boolean = true;
    }
}