/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.granite.tide.uibuilder {
	
    public interface IUIBuilder {
    	
    	function buildListColumns(metadata:Array, labelFunction:Function):Array;
    	
    	function buildEditForm(metadata:Array, form:Object):Array;
    }
}