/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.granite.tide.uibuilder {
	
	import flash.display.DisplayObjectContainer;
	

    public interface IUIFormLayout {
    	
    	function layoutEditForm(container:DisplayObjectContainer, properties:Array):void;
    }
}